### ISSUE TITLE
As an internal user I want to view the internal site after logging in so that I can access staff only processes

### ISSUE THREAD

**Issue by bryanmehsmith** [bryanmehsmith/espaza#53]
User Acceptance Test

Given that the internal has logged in
When they click on the internal site button
Then they should be routed to the internal site

**Comment by GimbiyaSa** [comment]
Hey @bryanmehsmith I've merged these changes to dev
I initially added the routes to index.js then it caused some merge conflicts when I tried to merge so I removed the edits I made
Saw some changes were made on the addHF function so not sure if that's why
